services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
      - proxy
    env_file: .env
    environment:
      QUEUE_ENABLED: "false"
      REDIS_URL: ""
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1536M
        reservations:
          cpus: "0.5"
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nba-app.rule=Host(`access.signauxx.com`)"
      - "traefik.http.routers.nba-app.entrypoints=websecure"
      - "traefik.http.routers.nba-app.tls=true"
      - "traefik.http.routers.nba-app.tls.certresolver=myresolver"
      - "traefik.http.services.nba-app.loadbalancer.server.port=3000"

networks:
  default:
  proxy:
    external: true
