export const ErrorCode = {
  AUTH_UNAUTHENTICATED: "AUTH_001",
  AUTH_SUSPENDED: "AUTH_002",
  AUTH_FORBIDDEN: "AUTH_003",
  AUTH_INACTIVE: "AUTH_004",
  AUTH_SESSION_EXPIRED: "AUTH_005",

  VALIDATION_ERROR: "VAL_001",
  VALIDATION_INVALID_INPUT: "VAL_002",
  VALIDATION_MISSING_FIELD: "VAL_003",

  NOT_FOUND: "RES_001",
  CONFLICT: "RES_002",
  RATE_LIMIT: "RL_001",
  METHOD_NOT_ALLOWED: "RES_003",

  DATABASE_ERROR: "DB_001",
  DATABASE_TIMEOUT: "DB_002",
  DATABASE_CONNECTION: "DB_003",
  DATABASE_RETRY_EXHAUSTED: "DB_004",

  CIRCUIT_OPEN: "EXT_001",
  EXTERNAL_API_ERROR: "EXT_002",
  EXTERNAL_TIMEOUT: "EXT_003",

  STORAGE_ERROR: "STO_001",
  UPLOAD_INVALID: "UPL_001",
  UPLOAD_TOO_LARGE: "UPL_002",

  INTERNAL_ERROR: "SYS_001",
  UNKNOWN_ERROR: "SYS_002",
  NOT_IMPLEMENTED: "SYS_003",
} as const

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode]
